Allow multi-argument runs of sui

diff --git a/sui b/sui
--- a/sui
+++ b/sui
@@ -1,16 +1,22 @@
 #!/bin/bash
 
-if [[ $# -eq 0 ]] ; then
-    echo 'Provide executable for sui'
-    exit 0
-fi
+sui() {
+  if [[ $# -eq 0 ]] ; then
+      echo 'Provide executable for sui'
+      return 1
+  fi
 
-app=$( which $1 )
+  declare app=$( which "$1" )
+  if [ $? -ne 0 ]; then
+    echo "Unable to find $1 through which, passing direct"
+    app=$1
+  fi
 
-if [ $? -ne 0 ]; then
-  echo "Unable to find $1 through which, passing direct"
-  app=$1
-fi
+  echo "水 $app"
+  chmod +s $app
+}
 
-echo "水 $app"
-chmod +s $app
+for comm in "$@"; do
+  sui $comm
+done
+
